# 建材兑换券名称和描述。
voucher:
  name: '&e[建材兑换券]'
  lore:
    - '&7输入命令/tianjiredeem打开兑换界面'

# 这里用于配置可兑换方块的方块ID。
# 使用 products: [] 可清空目录。
products:
  - minecraft:stone
  - minecraft:stone_bricks
  - minecraft:oak_planks
  - minecraft:glass
